config/routes.rb
Rails.application.routes.draw do
  get 'albums/show'
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  get 'users/update'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  
  root 'users#index'
  
  resources :users, only: [:index, :show, :edit, :update] do
    resources :albums, only: [:show]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :geolocation
  has_many :users
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :users
end

app/models/geolocation.rb
class Geolocation < ApplicationRecord
    has_one :address
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :album
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :address
  belongs_to :company
  has_many :albums, dependent: :destroy

  def photo_url
    "https://picsum.photos/id/#{id}/200/200" 
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ActionView::RecordIdentifier

  def index
    if params[:search]
      @users = User.where('username LIKE ?', "%#{params[:search]}%")
      flash.now[:alert] = "Kullanıcı Bulunamadı!" if @users.empty?
    else
      @users = User.all
    end
  end
  
  def edit
    @user = User.find(params[:id])
    @albums = @user.albums.includes(:photos)
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(dom_id(@user), partial: 'user', locals: { user: @user }),
            turbo_stream.replace("flash", partial: 'layouts/flash', locals: { notice: 'User was successfully updated.' })
          ]
        end
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      end
    else
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace(dom_id(@user, :edit), partial: 'form', locals: { user: @user }) }
        format.html { render :edit }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :phone, :website)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/show.html.erb
<h1><%= @album['title'] %></h1>
<p>Albüm Detayları:</p>

<ul>
  <% @photos.each do |photo| %>
    <li>
      <img src="<%= photo['thumbnailUrl'] %>" alt="<%= photo['title'] %>">
      <p><%= photo['title'] %></p>
    </li>
  <% end %>
</ul>

<%= link_to 'Geri', user_path(@album['userId']) %>

app/views/layouts/_flash.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserManagementApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="header-strip">
       <h1><%= link_to 'SOUNDERY', users_path, class: 'text-decoration-none text-dark' %></h1>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= turbo_frame_tag dom_id(user, :edit) do %>
  <%= form_with(model: user, local: false, data: { controller: 'modal', action: "turbo:submit-end->modal#closeModal" }) do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :username, class: 'form-label' %>
      <%= form.text_field :username, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :email, class: 'form-label' %>
      <%= form.text_field :email, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :phone, class: 'form-label' %>
      <%= form.text_field :phone, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :website, class: 'form-label' %>
      <%= form.text_field :website, class: 'form-control' %>
    </div>

    <%= form.submit "Update", class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/users/_user.html.erb
<%= turbo_frame_tag dom_id(user) do %>
  <div class="card mb-3">
    <div class="card-body text-center">
      <%= image_tag 'https://via.placeholder.com/150', class: 'rounded-circle mb-3', alt: 'user photo', size: "150x150" %>
      <h5 class="card-title"><%= user.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted">@<%= user.username %></h6>
      <p class="card-text">
        <strong>Email:</strong> <%= user.email %><br>
        <strong>Phone:</strong> <%= user.phone %><br>
        <strong>Address:</strong> Lorem Ipsum is simply dummy text of the printing and typesetting industry.
      </p>
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editUserModal">
        Edit
      </button>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>USER PROFILE</h1>

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="">
        <div class="card-body text-center">
          <%= turbo_frame_tag dom_id(@user) do %>
            <%= render 'user', user: @user %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-8">
      <h2>Albums</h2>
      <div class="list-group">
        <% @albums.each do |album| %>
          <a href="#albumModal" data-bs-toggle="modal" data-bs-target="#albumModal-<%= album.id %>" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 align-items-center">
              <img src="<%= album.photos.first&.thumbnail_url %>" class="img-thumbnail me-3" alt="album photo" style="width: 50px; height: 50px;">
              <h5 class="mb-1"><%= album.title %></h5>
            </div>
          </a>

          <div class="modal fade" id="albumModal-<%= album.id %>" tabindex="-1" aria-labelledby="albumModalLabel-<%= album.id %>" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="albumModalLabel-<%= album.id %>"><%= album.title %></h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <ul class="list-group">
                    <% album.photos.each do |photo| %>
                      <li class="list-group-item">
                        <img src="<%= photo.thumbnail_url %>" class="img-thumbnail me-3" alt="<%= photo.title %>" style="width: 100px; height: 100px;">
                        <%= photo.title %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="editUserModal" tabindex="-1" aria-labelledby="editUserModalLabel" aria-hidden="true" data-controller="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editUserModalLabel">Edit User</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= turbo_frame_tag dom_id(@user, :edit) do %>
          <%= render 'form', user: @user %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'users/index', media: 'all' %>
<% end %>

  <section> 
  <h1>USERS</h1>
  <%= form_with url: users_path, method: :get, local: true, class: "form-inline my-2 my-lg-0" do %>
    <div class="form-group mb-2">
      <%= label_tag :search, "SEARCH BY USERNAME:", class: "sr-only" %>
      <%= text_field_tag :search, params[:search], class: "form-control" %>
    </div>
    <%= submit_tag "SEARCH", class: "btn btn-primary mb-2" %>
    <%= link_to 'CLEAR', users_path, class: 'btn btn-secondary mb-2' %>
  <% end %>
  
  <% if flash.now[:alert] %>
    <div class="alert alert-warning my-2" role="alert">
      <%= flash.now[:alert] %>
    </div>
  <% end %>

  <ul class="list-group mt-4">
    <% @users.each do |user| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center">
          <img src="<%= user.photo_url %>" alt="user photo" class="img-thumbnail rounded-circle mr-3" style="width: 50px; height: 50px;">
          <div>
            <p class="mb-0"><%= user.name %></p>
            <small class="text-muted"><%= user.username %></small>
          </div>
        </div>
        <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-warning btn-sm' %>
      </li>
    <% end %>
  </ul>
</section>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>